Fixes site-install error.
Error: `In SiteInstallCommands.php line 367: Failed to drop or create the database:`
This is due because the `systemctl start mysql` command failed due to missing volume. Fix was to add the missing volume to the command.
Also, resolves #1856